### ISSUE TITLE
libgcc.a location is different

### ISSUE THREAD

**Issue by aldoridhoni** [DoctorWkt/xv6-freebsd#1]
I use fedora and i have to change the libgcc.a location.
`LIBGCC=/usr/lib/gcc/x86_64-redhat-linux/6.2.1/32/libgcc.a`
after installing the library
`# dnf install libgcc.i686`

**Comment by DoctorWkt** [comment]
Thanks for that comment. As I noted in the README, it is likely that you would need to edit Makefile.common and set LIBGCC to the location of libgcc.a. But your comment will help other Fedora users.
Cheers, Warren
